"""SynthFHIR — Synthetic FHIR Health Data Platform
======================================================
Production-quality Streamlit dashboard for exploring, comparing, evaluating,
and downloading synthetic EHR datasets generated by the SynthFHIR pipeline.

Run:
    streamlit run app.py
    streamlit run app.py -- --project-root /path/to/SynthFHIR
"""

from __future__ import annotations

import json
import os
import sys
import zipfile
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components

# ─── Project root resolution ───────────────────────────────────────────────────
_DEFAULT_ROOT = Path(__file__).parent.resolve()
PROJECT_ROOT  = Path(
    next((sys.argv[i + 1] for i, a in enumerate(sys.argv) if a == "--project-root"), None)
    or os.environ.get("PROJECT_ROOT", str(_DEFAULT_ROOT))
).resolve()

TABLES: list[str] = ["patients", "encounters", "observations", "conditions", "medications"]

TABLE_ICONS: dict[str, str] = {
    "patients":     "👤",
    "encounters":   "🏥",
    "observations": "🔬",
    "conditions":   "💊",
    "medications":  "💉",
}

# Plotly colour palette
_C = ["#38bdf8", "#818cf8", "#f472b6", "#34d399", "#fb923c", "#a78bfa"]

# ─── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title  = "SynthFHIR Platform",
    page_icon   = "🧬",
    layout      = "wide",
    initial_sidebar_state = "expanded",
)


# ══════════════════════════════════════════════════════════════════════════════
#  CSS — glassmorphism, dark theme, animations
# ══════════════════════════════════════════════════════════════════════════════
def inject_css() -> None:
    """Inject global dark-theme glassmorphism CSS."""
    st.markdown(
        """
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

/* ── Reset / base ─────────────────────────────────── */
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.main { background: #060b18; }
section[data-testid="stSidebar"] { background: linear-gradient(180deg,#090e1f 0%,#0d1425 60%,#090e1f 100%); border-right:1px solid rgba(56,189,248,0.12); }

/* ── Sidebar nav ──────────────────────────────────── */
section[data-testid="stSidebar"] .stRadio label {
    color:#94a3b8 !important; font-size:0.86rem; font-weight:400;
    padding:0.32rem 0.7rem; border-radius:8px; transition:all .18s;
    display:block; cursor:pointer;
}
section[data-testid="stSidebar"] .stRadio label:hover { color:#e2e8f0 !important; background:rgba(56,189,248,0.1); }
section[data-testid="stSidebar"] [data-testid="stMarkdownContainer"] p { color:#475569; font-size:0.7rem; letter-spacing:.08em; text-transform:uppercase; margin:1rem 0 .2rem .2rem; }

/* ── Glassmorphism card ───────────────────────────── */
.gcard {
    background:rgba(255,255,255,0.035); border:1px solid rgba(255,255,255,0.07);
    border-radius:16px; padding:1.25rem 1.5rem; backdrop-filter:blur(14px);
    -webkit-backdrop-filter:blur(14px); box-shadow:0 4px 28px rgba(0,0,0,0.35);
    margin-bottom:1rem;
}

/* ── KPI metric card ──────────────────────────────── */
.kcard {
    background:linear-gradient(135deg,rgba(56,189,248,0.1) 0%,rgba(129,140,248,0.07) 100%);
    border:1px solid rgba(56,189,248,0.22); border-radius:16px;
    padding:1.1rem 1.2rem; text-align:center;
    transition:transform .2s,box-shadow .2s;
    box-shadow:0 2px 14px rgba(56,189,248,0.1);
}
.kcard:hover { transform:translateY(-3px); box-shadow:0 8px 28px rgba(56,189,248,0.2); }
.kval { font-size:2rem; font-weight:800; background:linear-gradient(90deg,#38bdf8,#818cf8); -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; }
.klabel { font-size:0.72rem; color:#94a3b8; font-weight:600; letter-spacing:.06em; text-transform:uppercase; margin-top:.25rem; }
.ksub { font-size:0.7rem; color:#475569; margin-top:.1rem; }

/* ── Hero banner ──────────────────────────────────── */
.hero {
    background:linear-gradient(135deg,#05101f 0%,#0c1f42 45%,#05101f 100%);
    border:1px solid rgba(56,189,248,0.28); border-radius:20px;
    padding:1.8rem 2.2rem; margin-bottom:1.5rem; position:relative; overflow:hidden;
}
.hero::after { content:''; position:absolute; top:-80px; right:-80px; width:260px; height:260px;
    background:radial-gradient(circle,rgba(56,189,248,0.18) 0%,transparent 70%); pointer-events:none; }
.hero-title { font-size:1.85rem; font-weight:800; color:#e2e8f0; letter-spacing:-.025em; margin:0 0 .3rem; }
.hero-sub { font-size:.9rem; color:#64748b; margin:0; max-width:680px; line-height:1.65; }

/* ── Section header ───────────────────────────────── */
.sec-hdr { font-size:.95rem; font-weight:700; color:#e2e8f0;
    border-left:3px solid #38bdf8; padding-left:.7rem;
    margin:1.3rem 0 .75rem; letter-spacing:-.01em; }

/* ── Status chips ─────────────────────────────────── */
.chip-ok   { display:inline-block; padding:2px 10px; border-radius:99px; background:#0d3321; color:#4ade80; font-size:.72rem; font-weight:700; }
.chip-warn { display:inline-block; padding:2px 10px; border-radius:99px; background:#3b1f05; color:#fb923c; font-size:.72rem; font-weight:700; }
.chip-err  { display:inline-block; padding:2px 10px; border-radius:99px; background:#3b0505; color:#f87171; font-size:.72rem; font-weight:700; }
.chip-na   { display:inline-block; padding:2px 10px; border-radius:99px; background:#1e293b; color:#64748b; font-size:.72rem; font-weight:700; }

/* ── Score pills ──────────────────────────────────── */
.pill-good { display:inline-block; padding:3px 12px; border-radius:99px; background:#14532d; color:#86efac; font-size:.78rem; font-weight:700; }
.pill-fair { display:inline-block; padding:3px 12px; border-radius:99px; background:#713f12; color:#fde68a; font-size:.78rem; font-weight:700; }
.pill-poor { display:inline-block; padding:3px 12px; border-radius:99px; background:#7f1d1d; color:#fca5a5; font-size:.78rem; font-weight:700; }
.pill-na   { display:inline-block; padding:3px 12px; border-radius:99px; background:#1e293b; color:#64748b; font-size:.78rem; font-weight:700; }

/* ── Pipeline step ────────────────────────────────── */
.pip-step { display:inline-block; background:rgba(56,189,248,0.1); border:1px solid rgba(56,189,248,0.2);
    border-radius:8px; padding:.45rem .9rem; margin:.2rem; font-size:.78rem; color:#7dd3fc; font-weight:600; }
.pip-arr  { color:#334155; font-size:1.1rem; vertical-align:middle; }

/* ── Download button ──────────────────────────────── */
.stDownloadButton>button { background:linear-gradient(135deg,#0ea5e9,#6366f1) !important;
    color:#fff !important; border:none !important; border-radius:9px !important;
    font-weight:700 !important; font-size:.82rem !important;
    padding:.45rem 1.1rem !important; transition:all .18s !important; }
.stDownloadButton>button:hover { opacity:.85 !important; transform:translateY(-1px) !important; }

/* ── Tabs ─────────────────────────────────────────── */
.stTabs [data-baseweb="tab-list"] { background:rgba(255,255,255,0.025); border-radius:11px; padding:3px; gap:2px; }
.stTabs [data-baseweb="tab"]      { border-radius:9px; color:#64748b; font-weight:600; font-size:.82rem; }
.stTabs [aria-selected="true"]    { background:rgba(56,189,248,0.18) !important; color:#7dd3fc !important; }

/* ── DataFrame ────────────────────────────────────── */
.stDataFrame { border-radius:12px; overflow:hidden; }

/* ── Footer ───────────────────────────────────────── */
.footer { margin-top:3rem; padding:1rem 0 .4rem; border-top:1px solid rgba(255,255,255,0.06);
    text-align:center; font-size:.72rem; color:#334155; }

/* ── Expander ─────────────────────────────────────── */
details summary { color:#94a3b8 !important; font-weight:600 !important; font-size:.84rem !important; }

/* ── Horizontal rule ──────────────────────────────── */
hr { border-color:rgba(255,255,255,0.07) !important; margin:1.2rem 0 !important; }
</style>
""",
        unsafe_allow_html=True,
    )


# ══════════════════════════════════════════════════════════════════════════════
#  Data loaders  (all cached)
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=300, show_spinner=False)
def load_csv(path: str) -> Optional[pd.DataFrame]:
    """Load a CSV file into a DataFrame, returning None if missing or unreadable."""
    p = Path(path)
    if not p.exists():
        return None
    try:
        return pd.read_csv(p, low_memory=False)
    except Exception:
        return None


@st.cache_data(ttl=300, show_spinner=False)
def load_json(path: str) -> Optional[dict]:
    """Load a JSON file, returning None if missing or unreadable."""
    p = Path(path)
    if not p.exists():
        return None
    try:
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


@st.cache_data(ttl=300, show_spinner=False)
def load_html(path: str) -> Optional[str]:
    """Load an HTML file as a string."""
    p = Path(path)
    return p.read_text(encoding="utf-8") if p.exists() else None


@st.cache_data(ttl=300, show_spinner=False)
def read_bytes(path: str) -> Optional[bytes]:
    """Read raw bytes from a file."""
    p = Path(path)
    return p.read_bytes() if p.exists() else None


def synth_path(table: str) -> str:
    return str(PROJECT_ROOT / "outputs" / "synthetic" / f"synthetic_{table}.csv")


def orig_path(table: str) -> str:
    return str(PROJECT_ROOT / "data" / "ready" / f"{table}_ready.csv")


def model_path(table: str) -> str:
    return str(PROJECT_ROOT / "outputs" / "models" / f"{table}_model.pkl")


# ══════════════════════════════════════════════════════════════════════════════
#  Reusable UI helpers
# ══════════════════════════════════════════════════════════════════════════════

def metric_card(value: str, label: str, sub: str = "") -> str:
    """Return HTML for a single animated KPI card."""
    return (
        f'<div class="kcard">'
        f'<div class="kval">{value}</div>'
        f'<div class="klabel">{label}</div>'
        f'<div class="ksub">{sub}</div>'
        f'</div>'
    )


def glass_card(content: str) -> None:
    """Render arbitrary HTML inside a glassmorphism card."""
    st.markdown(f'<div class="gcard">{content}</div>', unsafe_allow_html=True)


def section_title(text: str) -> None:
    """Render a styled section header."""
    st.markdown(f'<div class="sec-hdr">{text}</div>', unsafe_allow_html=True)


def status_chip(ok: bool | None, label_ok: str = "Ready", label_no: str = "Missing") -> str:
    """Return an HTML status chip string."""
    if ok is None:
        return f'<span class="chip-na">N/A</span>'
    if ok:
        return f'<span class="chip-ok">{label_ok}</span>'
    return f'<span class="chip-warn">{label_no}</span>'


def score_pill(score: float | None) -> str:
    """Return a coloured score pill."""
    if score is None:
        return '<span class="pill-na">N/A</span>'
    if score >= 0.80:
        return f'<span class="pill-good">GOOD {score:.3f}</span>'
    if score >= 0.60:
        return f'<span class="pill-fair">FAIR {score:.3f}</span>'
    return f'<span class="pill-poor">POOR {score:.3f}</span>'


def render_footer() -> None:
    """Render page footer."""
    st.markdown(
        '<div class="footer">SynthFHIR · Synthetic FHIR Health Data Platform · '
        "SDV 1.37 · PyTorch · Streamlit · Plotly</div>",
        unsafe_allow_html=True,
    )


# ══════════════════════════════════════════════════════════════════════════════
#  Plotly helpers
# ══════════════════════════════════════════════════════════════════════════════

_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(color="#94a3b8", family="Inter, sans-serif", size=11),
    margin=dict(l=8, r=8, t=38, b=8),
    xaxis=dict(gridcolor="rgba(255,255,255,0.05)", linecolor="rgba(255,255,255,0.06)", zeroline=False),
    yaxis=dict(gridcolor="rgba(255,255,255,0.05)", linecolor="rgba(255,255,255,0.06)", zeroline=False),
    legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor="rgba(255,255,255,0.07)", borderwidth=1),
    hoverlabel=dict(bgcolor="#0f172a", bordercolor="#334155", font_color="#e2e8f0"),
    colorway=_C,
)


def theme(fig: go.Figure) -> go.Figure:
    """Apply dark theme to any Plotly figure."""
    fig.update_layout(**_LAYOUT)
    return fig


def plot_histogram_compare(
    real: pd.Series,
    synth: pd.Series,
    col: str,
    bins: int = 40,
) -> go.Figure:
    """Overlay histogram comparing original vs synthetic for a numeric column."""
    fig = go.Figure()
    fig.add_trace(go.Histogram(
        x=real, name="Original", nbinsx=bins,
        histnorm="probability density", opacity=0.62,
        marker_color="#38bdf8", hovertemplate="%{x}<br>density=%{y:.4f}<extra>Original</extra>",
    ))
    fig.add_trace(go.Histogram(
        x=synth, name="Synthetic", nbinsx=bins,
        histnorm="probability density", opacity=0.62,
        marker_color="#f472b6", hovertemplate="%{x}<br>density=%{y:.4f}<extra>Synthetic</extra>",
    ))
    fig.update_layout(barmode="overlay", title=f"Distribution — {col}",
                      legend=dict(orientation="h", y=1.08))
    return theme(fig)


def plot_category_compare(
    real: pd.Series,
    synth: pd.Series,
    col: str,
    top_n: int = 15,
) -> go.Figure:
    """Grouped bar chart comparing original vs synthetic category frequencies."""
    r = real.value_counts(normalize=True).head(top_n)
    s = synth.value_counts(normalize=True).head(top_n)
    cats = sorted(set(r.index) | set(s.index))
    fig = go.Figure()
    fig.add_trace(go.Bar(x=cats, y=[r.get(c, 0) for c in cats], name="Original",
                         marker_color="#38bdf8", hovertemplate="%{x}: %{y:.3f}<extra>Original</extra>"))
    fig.add_trace(go.Bar(x=cats, y=[s.get(c, 0) for c in cats], name="Synthetic",
                         marker_color="#f472b6", hovertemplate="%{x}: %{y:.3f}<extra>Synthetic</extra>"))
    fig.update_layout(barmode="group", title=f"Category Frequencies — {col}",
                      legend=dict(orientation="h", y=1.08))
    return theme(fig)


def plot_missing_values(df_orig: pd.DataFrame, df_synth: pd.DataFrame) -> go.Figure:
    """Bar chart of missing-value percentages for shared columns."""
    shared = [c for c in df_orig.columns if c in df_synth.columns]
    orig_m  = [round(df_orig[c].isna().mean() * 100, 2) for c in shared]
    synth_m = [round(df_synth[c].isna().mean() * 100, 2) for c in shared]
    df = pd.DataFrame({"Column": shared, "Original": orig_m, "Synthetic": synth_m})
    df = df[(df["Original"] > 0) | (df["Synthetic"] > 0)]
    if df.empty:
        fig = go.Figure()
        fig.add_annotation(text="No missing values in either dataset", showarrow=False,
                           font=dict(color="#64748b", size=14))
        return theme(fig)
    fig = go.Figure()
    fig.add_trace(go.Bar(x=df["Column"], y=df["Original"],  name="Original",  marker_color="#38bdf8"))
    fig.add_trace(go.Bar(x=df["Column"], y=df["Synthetic"], name="Synthetic", marker_color="#f472b6"))
    fig.update_layout(barmode="group", title="Missing Values (%)", yaxis_title="%",
                      legend=dict(orientation="h", y=1.08))
    return theme(fig)


def plot_heatmap(matrix: pd.DataFrame, title: str) -> go.Figure:
    """Plotly imshow heatmap."""
    fig = px.imshow(
        matrix.round(3),
        text_auto=".2f",
        color_continuous_scale=["#0c1a2e", "#0ea5e9", "#e2e8f0"],
        title=title,
        aspect="auto",
    )
    fig.update_traces(hovertemplate="%{x} × %{y}: %{z:.3f}<extra></extra>")
    return theme(fig)


def download_button(data: bytes, filename: str, label: str, mime: str = "text/csv") -> None:
    """Streamlit download button wrapper."""
    st.download_button(label=label, data=data, file_name=filename, mime=mime)


# ══════════════════════════════════════════════════════════════════════════════
#  Sidebar
# ══════════════════════════════════════════════════════════════════════════════

def render_sidebar() -> str:
    """Render the sidebar and return the selected page label."""
    with st.sidebar:
        # Logo + title
        st.markdown(
            """
<div style="text-align:center;padding:1.2rem 0 1.8rem">
  <div style="font-size:2.8rem;line-height:1">🧬</div>
  <div style="font-size:1.15rem;font-weight:800;color:#e2e8f0;margin-top:.4rem;letter-spacing:-.02em">SynthFHIR</div>
  <div style="font-size:.65rem;color:#334155;margin-top:.15rem;letter-spacing:.1em">SYNTHETIC HEALTH DATA PLATFORM</div>
</div>
""",
            unsafe_allow_html=True,
        )

        # Global score badge
        ev = load_json(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.json"))
        gs = ev.get("global_score") if ev else None
        pill = score_pill(gs)
        st.markdown(
            f"""
<div class="gcard" style="text-align:center;padding:.9rem .8rem .8rem">
  <div style="font-size:.65rem;color:#475569;letter-spacing:.08em;margin-bottom:.4rem">GLOBAL QUALITY SCORE</div>
  <div style="font-size:1.9rem;font-weight:800;background:linear-gradient(90deg,#38bdf8,#818cf8);
    -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text">
    {f"{gs:.3f}" if gs is not None else "—"}
  </div>
  <div style="margin-top:.35rem">{pill}</div>
</div>
""",
            unsafe_allow_html=True,
        )

        # Model status
        st.markdown("**Model Status**")
        for t in TABLES:
            m_ok = Path(model_path(t)).exists()
            s_ok = Path(synth_path(t)).exists()
            st.markdown(
                f'<div style="display:flex;align-items:center;gap:.5rem;margin:.18rem 0;font-size:.78rem;color:#64748b">'
                f'{TABLE_ICONS[t]} {t.capitalize()}&nbsp;'
                f'{status_chip(m_ok,"Model","No model")}&nbsp;{status_chip(s_ok,"Synth","No synth")}'
                f'</div>',
                unsafe_allow_html=True,
            )

        st.markdown("---")
        st.markdown("**Navigation**")

        pages = [
            "🏠  Dashboard",
            "👤  Patients",
            "🏥  Encounters",
            "🔬  Observations",
            "💊  Conditions",
            "💉  Medications",
            "📊  Evaluation",
            "📈  Analytics",
            "📥  Downloads",
            "ℹ️  About",
        ]
        choice = st.radio("nav", pages, label_visibility="collapsed")

        st.markdown("---")
        st.markdown(
            '<div style="text-align:center;font-size:.65rem;color:#1e293b;padding-bottom:.5rem">'
            "SDV 1.37 · PAR · CTGAN · GaussianCopula</div>",
            unsafe_allow_html=True,
        )

    return choice


# ══════════════════════════════════════════════════════════════════════════════
#  Page 1 — Dashboard
# ══════════════════════════════════════════════════════════════════════════════

def page_dashboard() -> None:
    """Main dashboard: KPIs, row comparison, quality chart, pipeline, status."""
    # Hero
    st.markdown(
        """
<div class="hero">
  <div class="hero-title">🧬 SynthFHIR Analytics Platform</div>
  <p class="hero-sub">Privacy-preserving synthetic FHIR health records · PAR · CTGAN · GaussianCopula · Fully evaluated</p>
</div>
""",
        unsafe_allow_html=True,
    )

    # ── KPI row ─────────────────────────────────────────────────────────────
    total_orig = total_synth = 0
    for t in TABLES:
        o = load_csv(orig_path(t));  total_orig  += len(o)  if o  is not None else 0
        s = load_csv(synth_path(t)); total_synth += len(s)  if s  is not None else 0

    ev   = load_json(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.json"))
    gs   = ev.get("global_score") if ev else None
    n_models = sum(1 for t in TABLES if Path(model_path(t)).exists())
    n_synth  = sum(1 for t in TABLES if Path(synth_path(t)).exists())

    kpis = [
        (f"{total_orig:,}",  "Original Records",  "across 5 tables"),
        (f"{total_synth:,}", "Synthetic Records",  "generated"),
        (f"{n_models}/5",    "Models Trained",     "SDV synthesizers"),
        (f"{n_synth}/5",     "Tables Ready",       "synthetic CSVs"),
        (f"{gs:.3f}" if gs is not None else "—", "Quality Score", "Phase 5 evaluation"),
    ]
    cols = st.columns(len(kpis))
    for col, (v, l, s) in zip(cols, kpis):
        col.markdown(metric_card(v, l, s), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Row comparison chart + Quality chart ─────────────────────────────────
    cl, cr = st.columns([3, 2])

    with cl:
        section_title("Original vs Synthetic Row Counts")
        rows = []
        for t in TABLES:
            o = load_csv(orig_path(t)); s = load_csv(synth_path(t))
            rows.append({
                "Table":    t.capitalize(),
                "Original":  len(o) if o is not None else 0,
                "Synthetic": len(s) if s is not None else 0,
            })
        df_r = pd.DataFrame(rows)
        fig = go.Figure()
        fig.add_trace(go.Bar(x=df_r["Table"], y=df_r["Original"],  name="Original",
                             marker_color="#38bdf8", marker_line_width=0))
        fig.add_trace(go.Bar(x=df_r["Table"], y=df_r["Synthetic"], name="Synthetic",
                             marker_color="#818cf8", marker_line_width=0))
        fig.update_layout(barmode="group", title="", legend=dict(orientation="h", y=1.06))
        st.plotly_chart(theme(fig), use_container_width=True)

    with cr:
        section_title("Overall Quality by Table")
        if ev:
            ts = ev.get("scores", {}).get("tables", {})
            tbl_names   = [t.capitalize() for t in TABLES]
            tbl_overall = [ts.get(t, {}).get("overall") or 0 for t in TABLES]
            fig2 = go.Figure(go.Bar(
                x=tbl_names, y=tbl_overall,
                marker=dict(
                    color=tbl_overall,
                    colorscale=[[0,"#7f1d1d"],[0.6,"#713f12"],[1,"#14532d"]],
                    showscale=False,
                    line_width=0,
                ),
                text=[f"{v:.3f}" for v in tbl_overall],
                textposition="outside",
            ))
            fig2.update_layout(yaxis=dict(range=[0, 1.12]), title="")
            st.plotly_chart(theme(fig2), use_container_width=True)
        else:
            st.info("Run `python run_phase5.py` to see quality scores.")

    # ── Pipeline diagram ─────────────────────────────────────────────────────
    section_title("Synthesis Pipeline")
    st.markdown(
        """
<div class="gcard" style="text-align:center;padding:1rem">
  <span class="pip-step">📁 FHIR JSON</span><span class="pip-arr"> → </span>
  <span class="pip-step">🔍 Parse &amp; Profile</span><span class="pip-arr"> → </span>
  <span class="pip-step">⚙️ Preprocess</span><span class="pip-arr"> → </span>
  <span class="pip-step">🧠 Train Models</span><span class="pip-arr"> → </span>
  <span class="pip-step">🎲 Sample</span><span class="pip-arr"> → </span>
  <span class="pip-step">📊 Evaluate</span><span class="pip-arr"> → </span>
  <span class="pip-step">🌐 Dashboard</span>
</div>
""",
        unsafe_allow_html=True,
    )

    # ── Per-table status cards ────────────────────────────────────────────────
    section_title("System Status")

    eval_ts = ev.get("generated_at", "—") if ev else "—"
    st.markdown(
        f'<div style="font-size:.75rem;color:#475569;margin-bottom:.6rem">Last evaluation: {eval_ts}</div>',
        unsafe_allow_html=True,
    )

    t_cols = st.columns(5)
    for col, t in zip(t_cols, TABLES):
        m_ok = Path(model_path(t)).exists()
        s_ok = Path(synth_path(t)).exists()
        e_ok = ev is not None and t in ev.get("scores", {}).get("tables", {})
        ov   = (ev.get("scores", {}).get("tables", {}).get(t, {}).get("overall")
                if ev else None)
        col.markdown(
            f"""
<div class="gcard" style="text-align:center;padding:.9rem .7rem">
  <div style="font-size:1.8rem">{TABLE_ICONS[t]}</div>
  <div style="font-size:.82rem;font-weight:700;color:#e2e8f0;margin:.3rem 0">{t.capitalize()}</div>
  {status_chip(m_ok,"Model","No model")}<br>
  <div style="margin:.2rem 0">{status_chip(s_ok,"Synth","Missing")}</div>
  <div style="margin:.2rem 0">{status_chip(e_ok,"Evaluated","Not run")}</div>
  <div style="margin-top:.4rem;font-size:.8rem;color:#94a3b8">{f"Score: <b>{ov:.3f}</b>" if ov else ""}</div>
</div>
""",
            unsafe_allow_html=True,
        )

    render_footer()


# ══════════════════════════════════════════════════════════════════════════════
#  Page 2-6 — Generic dataset page (customised per table)
# ══════════════════════════════════════════════════════════════════════════════

def _col_of(df: pd.DataFrame, *keywords: str) -> Optional[str]:
    """Find first column whose name contains any keyword (case-insensitive)."""
    for kw in keywords:
        for c in df.columns:
            if kw.lower() in c.lower():
                return c
    return None


def _numeric_col_selector(df_o: pd.DataFrame, df_s: pd.DataFrame, key: str) -> Optional[str]:
    num = [c for c in df_o.columns if c in df_s.columns
           and pd.api.types.is_numeric_dtype(df_o[c])
           and not pd.api.types.is_bool_dtype(df_o[c])
           and df_o[c].nunique() > 2]
    return st.selectbox("Numeric column", num, key=key) if num else None


def _cat_col_selector(df_o: pd.DataFrame, df_s: pd.DataFrame, key: str) -> Optional[str]:
    cats = [c for c in df_o.columns if c in df_s.columns
            and (df_o[c].dtype == object or pd.api.types.is_bool_dtype(df_o[c]))
            and df_o[c].nunique() <= 40]
    return st.selectbox("Categorical column", cats, key=key) if cats else None


def page_dataset(table: str) -> None:
    """Generic dataset exploration page used for all 5 tables."""
    icon  = TABLE_ICONS[table]
    title = table.capitalize()

    st.markdown(
        f'<div class="hero"><div class="hero-title">{icon} {title}</div>'
        f'<p class="hero-sub">Explore original and synthetic {title} records side by side.</p></div>',
        unsafe_allow_html=True,
    )

    df_o = load_csv(orig_path(table))
    df_s = load_csv(synth_path(table))

    # KPI row
    kpi_c = st.columns(4)
    for col, (v, l) in zip(kpi_c, [
        (f"{len(df_o):,}" if df_o is not None else "—", "Original Rows"),
        (f"{len(df_s):,}" if df_s is not None else "—", "Synthetic Rows"),
        (f"{len(df_o.columns)}" if df_o is not None else "—", "Columns (orig)"),
        (f"{df_o.isnull().mean().mean()*100:.1f}%" if df_o is not None else "—", "Avg Missing"),
    ]):
        col.markdown(metric_card(v, l), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    tab_o, tab_s, tab_cmp, tab_stat = st.tabs(
        ["📂 Original", "🎲 Synthetic", "⚖️ Comparison", "📐 Statistics"]
    )

    # ── Original ──────────────────────────────────────────────────────────────
    with tab_o:
        if df_o is None:
            st.warning(f"`data/ready/{table}_ready.csv` not found.")
        else:
            col_sel = st.multiselect("Columns", df_o.columns.tolist(),
                                     default=df_o.columns[:8].tolist(), key=f"cols_o_{table}")
            search  = st.text_input("Search (any value)", key=f"srch_o_{table}", placeholder="Filter rows…")
            disp    = df_o[col_sel] if col_sel else df_o
            if search:
                mask = disp.apply(lambda c: c.astype(str).str.contains(search, case=False, na=False)).any(1)
                disp = disp[mask]
            st.caption(f"{len(disp):,} / {len(df_o):,} rows")
            st.dataframe(disp.head(500), use_container_width=True, height=360)
            b = read_bytes(orig_path(table))
            if b:
                download_button(b, f"{table}_ready.csv", f"⬇ Download {title} Original CSV")

    # ── Synthetic ─────────────────────────────────────────────────────────────
    with tab_s:
        if df_s is None:
            st.warning(f"`outputs/synthetic/synthetic_{table}.csv` not found. Run Phase 4B.")
        else:
            col_sel2 = st.multiselect("Columns", df_s.columns.tolist(),
                                      default=df_s.columns[:8].tolist(), key=f"cols_s_{table}")
            search2  = st.text_input("Search (any value)", key=f"srch_s_{table}", placeholder="Filter rows…")
            disp2    = df_s[col_sel2] if col_sel2 else df_s
            if search2:
                mask2 = disp2.apply(lambda c: c.astype(str).str.contains(search2, case=False, na=False)).any(1)
                disp2 = disp2[mask2]
            st.caption(f"{len(disp2):,} / {len(df_s):,} rows")
            st.dataframe(disp2.head(500), use_container_width=True, height=360)
            b2 = read_bytes(synth_path(table))
            if b2:
                download_button(b2, f"synthetic_{table}.csv", f"⬇ Download {title} Synthetic CSV")

    # ── Comparison ────────────────────────────────────────────────────────────
    with tab_cmp:
        if df_o is None or df_s is None:
            st.info("Both original and synthetic data must be present to compare.")
        else:
            c1, c2 = st.columns(2)
            with c1:
                num_col = _numeric_col_selector(df_o, df_s, f"num_{table}")
                if num_col:
                    r = pd.to_numeric(df_o[num_col], errors="coerce").dropna()
                    s = pd.to_numeric(df_s[num_col], errors="coerce").dropna()
                    st.plotly_chart(plot_histogram_compare(r, s, num_col),
                                    use_container_width=True)
            with c2:
                cat_col = _cat_col_selector(df_o, df_s, f"cat_{table}")
                if cat_col:
                    st.plotly_chart(
                        plot_category_compare(df_o[cat_col], df_s[cat_col], cat_col),
                        use_container_width=True,
                    )

            section_title("Missing Values")
            st.plotly_chart(plot_missing_values(df_o, df_s), use_container_width=True)

            # Table-specific visualizations
            _table_specific_charts(table, df_o, df_s)

    # ── Statistics ────────────────────────────────────────────────────────────
    with tab_stat:
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Original — describe()**")
            if df_o is not None:
                st.dataframe(df_o.describe(include="all").round(3), use_container_width=True, height=320)
        with c2:
            st.markdown("**Synthetic — describe()**")
            if df_s is not None:
                st.dataframe(df_s.describe(include="all").round(3), use_container_width=True, height=320)

        if df_o is not None and df_s is not None:
            section_title("Correlation Matrix — Original")
            num_df_o = df_o.select_dtypes(include="number")
            if not num_df_o.empty and num_df_o.shape[1] >= 2:
                st.plotly_chart(
                    plot_heatmap(num_df_o.corr(), "Correlation Matrix (Original)"),
                    use_container_width=True,
                )

    render_footer()


def _table_specific_charts(table: str, df_o: pd.DataFrame, df_s: pd.DataFrame) -> None:
    """Render extra visualizations specific to each table."""
    section_title("Table-Specific Analysis")

    if table == "patients":
        cols = st.columns(3)
        for col, kw, title in [
            (cols[0], ("age",),      "Age Distribution"),
            (cols[1], ("gender","sex"), "Gender Distribution"),
            (cols[2], ("race","ethnicity"), "Race / Ethnicity"),
        ]:
            c = _col_of(df_o, *kw)
            if c is None:
                continue
            with col:
                if pd.api.types.is_numeric_dtype(df_o[c]):
                    r = pd.to_numeric(df_o[c], errors="coerce").dropna()
                    s = pd.to_numeric(df_s[c], errors="coerce").dropna()
                    col.plotly_chart(plot_histogram_compare(r, s, c), use_container_width=True)
                else:
                    col.plotly_chart(plot_category_compare(df_o[c], df_s[c], c), use_container_width=True)

    elif table == "encounters":
        cols = st.columns(2)
        for col, kw in [(cols[0], ("class","type","encounter")), (cols[1], ("duration","length","stay"))]:
            c = _col_of(df_o, *kw)
            if c is None:
                continue
            with col:
                if pd.api.types.is_numeric_dtype(df_o[c]):
                    r = pd.to_numeric(df_o[c], errors="coerce").dropna()
                    s = pd.to_numeric(df_s[c], errors="coerce").dropna()
                    col.plotly_chart(plot_histogram_compare(r, s, c), use_container_width=True)
                else:
                    col.plotly_chart(plot_category_compare(df_o[c], df_s[c], c), use_container_width=True)

    elif table == "observations":
        val_c  = _col_of(df_o, "value", "result")
        unit_c = _col_of(df_o, "unit", "units")
        cat_c  = _col_of(df_o, "description", "category", "type")
        if val_c and pd.api.types.is_numeric_dtype(df_o[val_c]):
            r = pd.to_numeric(df_o[val_c], errors="coerce").dropna()
            s = pd.to_numeric(df_s[val_c], errors="coerce").dropna()
            st.plotly_chart(plot_histogram_compare(r, s, val_c), use_container_width=True)
        if cat_c:
            st.plotly_chart(plot_category_compare(df_o[cat_c], df_s[cat_c], cat_c), use_container_width=True)

    elif table == "conditions":
        desc_c    = _col_of(df_o, "description", "code", "condition")
        chronic_c = _col_of(df_o, "chronic", "is_chronic")
        cols = st.columns(2)
        if desc_c:
            with cols[0]:
                st.plotly_chart(plot_category_compare(df_o[desc_c], df_s[desc_c], desc_c, top_n=12),
                                use_container_width=True)
        if chronic_c:
            with cols[1]:
                st.plotly_chart(plot_category_compare(df_o[chronic_c], df_s[chronic_c], chronic_c),
                                use_container_width=True)

    elif table == "medications":
        med_c    = _col_of(df_o, "description", "medication", "drug")
        route_c  = _col_of(df_o, "route", "dispense")
        status_c = _col_of(df_o, "status", "active")
        cols = st.columns(2 if (route_c or status_c) else 1)
        if med_c:
            cols[0].plotly_chart(
                plot_category_compare(df_o[med_c], df_s[med_c], med_c, top_n=12),
                use_container_width=True,
            )
        if route_c and len(cols) > 1:
            cols[1].plotly_chart(
                plot_category_compare(df_o[route_c], df_s[route_c], route_c),
                use_container_width=True,
            )


# ══════════════════════════════════════════════════════════════════════════════
#  Page 7 — Evaluation
# ══════════════════════════════════════════════════════════════════════════════

def page_evaluation() -> None:
    """Phase 5 evaluation dashboard: gauges, cards, radar, HTML report."""
    st.markdown(
        """
<div class="hero">
  <div class="hero-title">📊 Phase 5 Evaluation</div>
  <p class="hero-sub">KS similarity · TVD · Pearson correlation preservation · Privacy score · SDV quality</p>
</div>
""",
        unsafe_allow_html=True,
    )

    ev = load_json(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.json"))

    if ev is None:
        st.warning("No evaluation results. Run `python run_phase5.py` to generate them.")
        render_footer()
        return

    gs = ev.get("global_score")
    ts = ev.get("scores", {}).get("tables", {})

    # ── Gauge + metadata ─────────────────────────────────────────────────────
    g_col, m_col = st.columns([1, 2])

    with g_col:
        val = round((gs or 0) * 100, 1)
        fig_g = go.Figure(go.Indicator(
            mode="gauge+number",
            value=val,
            number={"suffix": "%", "font": {"color": "#e2e8f0", "size": 30, "family": "Inter"}},
            title={"text": "Global Quality", "font": {"color": "#64748b", "size": 12}},
            gauge={
                "axis": {"range": [0, 100], "tickfont": {"color": "#475569"}},
                "bar":  {"color": "#38bdf8", "thickness": 0.22},
                "bgcolor": "rgba(0,0,0,0)",
                "bordercolor": "rgba(255,255,255,0.08)",
                "steps": [
                    {"range": [0, 60],   "color": "rgba(239,68,68,0.12)"},
                    {"range": [60, 80],  "color": "rgba(245,158,11,0.12)"},
                    {"range": [80, 100], "color": "rgba(16,185,129,0.12)"},
                ],
            },
        ))
        fig_g.update_layout(paper_bgcolor="rgba(0,0,0,0)", font=dict(family="Inter"),
                             height=240, margin=dict(l=20, r=20, t=20, b=10))
        st.plotly_chart(fig_g, use_container_width=True)

    with m_col:
        section_title("Score Interpretation")
        glass_card(
            """
<table style="width:100%;border-collapse:collapse;font-size:.8rem;color:#94a3b8">
<tr><td style="padding:5px 10px"><span class="pill-good">GOOD</span></td>
    <td style="padding:5px 10px">≥ 0.80</td>
    <td style="padding:5px 10px">Excellent fidelity — suitable for ML training &amp; analytics</td></tr>
<tr style="background:rgba(255,255,255,.02)">
    <td style="padding:5px 10px"><span class="pill-fair">FAIR</span></td>
    <td style="padding:5px 10px">0.60 – 0.79</td>
    <td style="padding:5px 10px">Acceptable quality — verify per use-case</td></tr>
<tr><td style="padding:5px 10px"><span class="pill-poor">POOR</span></td>
    <td style="padding:5px 10px">&lt; 0.60</td>
    <td style="padding:5px 10px">Low fidelity — review synthesis config or increase epochs</td></tr>
</table>
<div style="margin-top:.7rem;font-size:.73rem;color:#475569">
  Weights: Numeric ×3 · Categorical ×3 · Correlation ×2 · Privacy ×2
</div>
"""
        )
        glass_card(
            f'<div style="font-size:.73rem;color:#475569">Generated: {ev.get("generated_at","—")}</div>'
            f'<div style="font-size:.73rem;color:#475569;margin-top:.3rem">'
            f'Tables: {", ".join(ev.get("tables_evaluated",[]))}</div>'
        )

    # ── Metric cards per dimension ────────────────────────────────────────────
    section_title("Dimension Metric Cards")
    dim_keys = [
        ("numeric_similarity",       "Numeric Similarity",   "KS-test"),
        ("categorical_similarity",   "Categorical",          "TVD"),
        ("correlation_preservation", "Correlation",          "Pearson"),
        ("privacy_score",            "Privacy",              "Uniqueness × Overlap"),
    ]
    mc = st.columns(len(dim_keys))
    for col, (key, lbl, sub) in zip(mc, dim_keys):
        vals = [ts.get(t, {}).get(key) for t in TABLES if ts.get(t, {}).get(key) is not None]
        avg  = round(sum(vals) / len(vals), 3) if vals else None
        col.markdown(metric_card(f"{avg:.3f}" if avg else "—", lbl, sub), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Per-table expandable cards ────────────────────────────────────────────
    section_title("Per-Table Breakdown")
    for t in TABLES:
        s = ts.get(t, {})
        ov = s.get("overall")
        with st.expander(
            f"{TABLE_ICONS[t]}  {t.capitalize()}  —  Overall: {f'{ov:.3f}' if ov else 'N/A'}  "
            + ("GOOD" if ov and ov >= 0.80 else "FAIR" if ov and ov >= 0.60 else "POOR" if ov else "—"),
            expanded=False,
        ):
            cc = st.columns(5)
            for col, (key, lbl) in zip(cc, [
                ("numeric_similarity",       "Numeric"),
                ("categorical_similarity",   "Categorical"),
                ("correlation_preservation", "Correlation"),
                ("privacy_score",            "Privacy"),
                ("overall",                  "Overall"),
            ]):
                v = s.get(key)
                clr = "#4ade80" if v and v >= .80 else "#fde68a" if v and v >= .60 else "#f87171" if v else "#475569"
                col.markdown(
                    f'<div class="kcard">'
                    f'<div class="kval" style="font-size:1.4rem;background:none;-webkit-text-fill-color:{clr};color:{clr}">'
                    f'{f"{v:.3f}" if v else "—"}</div>'
                    f'<div class="klabel">{lbl}</div></div>',
                    unsafe_allow_html=True,
                )

    # ── Radar chart ───────────────────────────────────────────────────────────
    section_title("Score Radar — All Tables")
    cats = ["Numeric", "Categorical", "Correlation", "Privacy"]
    keys = ["numeric_similarity", "categorical_similarity", "correlation_preservation", "privacy_score"]
    fig_r = go.Figure()
    for t, clr in zip(TABLES, _C):
        s   = ts.get(t, {})
        vals = [s.get(k) or 0 for k in keys]
        fig_r.add_trace(go.Scatterpolar(
            r=vals + [vals[0]], theta=cats + [cats[0]],
            fill="toself", name=t.capitalize(),
            line_color=clr, opacity=0.85,
        ))
    fig_r.update_layout(
        polar=dict(
            bgcolor="rgba(0,0,0,0)",
            radialaxis=dict(visible=True, range=[0, 1], tickfont=dict(color="#475569", size=9),
                            gridcolor="rgba(255,255,255,0.06)"),
            angularaxis=dict(tickfont=dict(color="#94a3b8"), gridcolor="rgba(255,255,255,0.06)"),
        ),
        paper_bgcolor="rgba(0,0,0,0)", font=dict(color="#94a3b8", family="Inter"),
        legend=dict(orientation="h", y=-0.15), height=420, margin=dict(l=40, r=40, t=10, b=60),
    )
    st.plotly_chart(fig_r, use_container_width=True)

    # ── CSV / JSON download ───────────────────────────────────────────────────
    section_title("Download Evaluation Outputs")
    dc1, dc2, dc3 = st.columns(3)

    ev_csv  = read_bytes(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.csv"))
    ev_json = read_bytes(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.json"))
    ev_html = read_bytes(str(PROJECT_ROOT / "outputs" / "evaluation" / "report.html"))

    with dc1:
        if ev_csv:
            download_button(ev_csv, "evaluation_summary.csv", "⬇ Evaluation CSV")
    with dc2:
        if ev_json:
            download_button(ev_json, "evaluation_summary.json", "⬇ Evaluation JSON", mime="application/json")
    with dc3:
        if ev_html:
            download_button(ev_html, "synthfhir_report.html", "⬇ HTML Report", mime="text/html")

    # ── Embedded HTML report ──────────────────────────────────────────────────
    html_src = load_html(str(PROJECT_ROOT / "outputs" / "evaluation" / "report.html"))
    if html_src:
        section_title("Embedded Evaluation Report")
        with st.expander("Expand full HTML report", expanded=False):
            components.html(html_src, height=900, scrolling=True)

    render_footer()


# ══════════════════════════════════════════════════════════════════════════════
#  Page 8 — Analytics
# ══════════════════════════════════════════════════════════════════════════════

def page_analytics() -> None:
    """Cross-table analytics: treemap, heatmap, scatter, boxplots, stacked bars."""
    st.markdown(
        """
<div class="hero">
  <div class="hero-title">📈 Analytics</div>
  <p class="hero-sub">Cross-table insights and deep-dive statistical analysis of the synthetic dataset.</p>
</div>
""",
        unsafe_allow_html=True,
    )

    tab_pt, tab_enc, tab_clin, tab_cross = st.tabs(
        ["👤 Patient Analytics", "🏥 Encounter Analytics", "💊 Clinical Analytics", "🔗 Cross-Table"]
    )

    # ── Patient analytics ─────────────────────────────────────────────────────
    with tab_pt:
        pts = load_csv(synth_path("patients"))
        if pts is None:
            st.info("Synthetic patients not available.")
        else:
            c1, c2 = st.columns(2)
            gender_c = _col_of(pts, "gender", "sex")
            age_c    = _col_of(pts, "age")
            race_c   = _col_of(pts, "race", "ethnicity")
            state_c  = _col_of(pts, "state", "county", "city")

            if gender_c:
                with c1:
                    g_cnt = pts[gender_c].value_counts().reset_index()
                    g_cnt.columns = ["Gender", "Count"]
                    fig_g = px.pie(g_cnt, names="Gender", values="Count",
                                   title="Gender Distribution", hole=0.42,
                                   color_discrete_sequence=_C)
                    st.plotly_chart(theme(fig_g), use_container_width=True)

            if age_c:
                with c2:
                    ages = pd.to_numeric(pts[age_c], errors="coerce").dropna()
                    fig_a = px.histogram(ages, nbins=30, title="Age Distribution",
                                         color_discrete_sequence=["#38bdf8"],
                                         labels={"value": "Age", "count": "Count"})
                    st.plotly_chart(theme(fig_a), use_container_width=True)

            if race_c:
                rc = pts[race_c].value_counts().head(10).reset_index()
                rc.columns = ["Race", "Count"]
                fig_r = px.bar(rc, x="Race", y="Count", title="Race / Ethnicity",
                               color="Count", color_continuous_scale=["#0c1a2e", "#38bdf8"])
                st.plotly_chart(theme(fig_r), use_container_width=True)

            if state_c:
                sc = pts[state_c].value_counts().head(15).reset_index()
                sc.columns = ["State", "Count"]
                fig_s = px.bar(sc, x="Count", y="State", orientation="h",
                               title="Top 15 States", color_discrete_sequence=["#818cf8"])
                st.plotly_chart(theme(fig_s), use_container_width=True)

    # ── Encounter analytics ───────────────────────────────────────────────────
    with tab_enc:
        enc = load_csv(synth_path("encounters"))
        if enc is None:
            st.info("Synthetic encounters not available.")
        else:
            c1, c2 = st.columns(2)
            cls_c  = _col_of(enc, "class", "type", "encounter")
            cost_c = _col_of(enc, "cost", "total", "base")
            dur_c  = _col_of(enc, "duration", "length", "stay")

            if cls_c:
                with c1:
                    ec = enc[cls_c].value_counts().head(12).reset_index()
                    ec.columns = ["Type", "Count"]
                    fig_ec = px.bar(ec, x="Count", y="Type", orientation="h",
                                    title="Encounter Types", color_discrete_sequence=["#06b6d4"])
                    st.plotly_chart(theme(fig_ec), use_container_width=True)

            if cost_c:
                with c2:
                    costs = pd.to_numeric(enc[cost_c], errors="coerce").dropna()
                    costs = costs.clip(0, costs.quantile(0.99))
                    fig_co = px.histogram(costs, nbins=40, title=f"Cost Distribution ({cost_c})",
                                          color_discrete_sequence=["#34d399"])
                    st.plotly_chart(theme(fig_co), use_container_width=True)

            if dur_c:
                dur = pd.to_numeric(enc[dur_c], errors="coerce").dropna()
                fig_dur = go.Figure(go.Box(y=dur, name="Duration", marker_color="#f472b6",
                                           boxpoints="outliers",
                                           hovertemplate="Value: %{y}<extra></extra>"))
                fig_dur.update_layout(title=f"Length of Stay — {dur_c}", showlegend=False)
                st.plotly_chart(theme(fig_dur), use_container_width=True)

    # ── Clinical analytics ────────────────────────────────────────────────────
    with tab_clin:
        cond = load_csv(synth_path("conditions"))
        meds = load_csv(synth_path("medications"))
        obs  = load_csv(synth_path("observations"))

        c1, c2 = st.columns(2)
        with c1:
            if cond is not None:
                dc = _col_of(cond, "description", "code")
                if dc:
                    top_c = cond[dc].value_counts().head(12).reset_index()
                    top_c.columns = ["Condition", "Count"]
                    fig_c = px.bar(top_c, x="Count", y="Condition", orientation="h",
                                   title="Top 12 Conditions", color_discrete_sequence=["#f59e0b"])
                    st.plotly_chart(theme(fig_c), use_container_width=True)

        with c2:
            if meds is not None:
                dm = _col_of(meds, "description", "medication", "drug")
                if dm:
                    top_m = meds[dm].value_counts().head(12).reset_index()
                    top_m.columns = ["Medication", "Count"]
                    fig_m = px.bar(top_m, x="Count", y="Medication", orientation="h",
                                   title="Top 12 Medications", color_discrete_sequence=["#ec4899"])
                    st.plotly_chart(theme(fig_m), use_container_width=True)

        if obs is not None:
            desc_c = _col_of(obs, "description", "category")
            val_c  = _col_of(obs, "value", "result")
            if desc_c and val_c and pd.api.types.is_numeric_dtype(obs[val_c]):
                top_types = obs[desc_c].value_counts().head(8).index.tolist()
                sel_type  = st.selectbox("Observation type", top_types, key="obs_type_analytics")
                sub_obs   = obs[obs[desc_c] == sel_type]
                vals      = pd.to_numeric(sub_obs[val_c], errors="coerce").dropna()
                if len(vals) > 0:
                    fig_ov = px.histogram(vals, nbins=35, title=f"Values: {sel_type}",
                                          color_discrete_sequence=["#818cf8"])
                    st.plotly_chart(theme(fig_ov), use_container_width=True)

    # ── Cross-table analytics ─────────────────────────────────────────────────
    with tab_cross:
        # Treemap of record counts
        rc = {t: len(load_csv(synth_path(t))) for t in TABLES if load_csv(synth_path(t)) is not None}
        if rc:
            df_rc = pd.DataFrame({"Table": list(rc.keys()), "Rows": list(rc.values())})
            fig_tm = px.treemap(df_rc, path=["Table"], values="Rows",
                                title="Synthetic Dataset — Record Distribution",
                                color="Rows",
                                color_continuous_scale=["#05101f", "#0ea5e9", "#e2e8f0"])
            st.plotly_chart(theme(fig_tm), use_container_width=True)

        # Evaluation score heatmap
        ev = load_json(str(PROJECT_ROOT / "outputs" / "evaluation" / "evaluation_summary.json"))
        if ev:
            ev_ts = ev.get("scores", {}).get("tables", {})
            heat_rows = []
            for t in TABLES:
                s = ev_ts.get(t, {})
                heat_rows.append({
                    "Table":       t.capitalize(),
                    "Numeric":     s.get("numeric_similarity")     or 0,
                    "Categorical": s.get("categorical_similarity") or 0,
                    "Correlation": s.get("correlation_preservation") or 0,
                    "Privacy":     s.get("privacy_score")          or 0,
                    "Overall":     s.get("overall")                or 0,
                })
            df_h = pd.DataFrame(heat_rows).set_index("Table")
            st.plotly_chart(plot_heatmap(df_h, "Evaluation Score Heatmap"), use_container_width=True)

        # Scatter: original rows vs overall score
        if ev:
            scatter_pts = []
            for t in TABLES:
                o  = load_csv(orig_path(t))
                ov = ev.get("scores", {}).get("tables", {}).get(t, {}).get("overall")
                if o is not None and ov is not None:
                    scatter_pts.append({"Table": t.capitalize(), "Rows": len(o), "Score": ov})
            if scatter_pts:
                df_sc = pd.DataFrame(scatter_pts)
                fig_sc = px.scatter(df_sc, x="Rows", y="Score", text="Table",
                                    title="Original Row Count vs Quality Score",
                                    color="Score",
                                    color_continuous_scale=["#7f1d1d", "#713f12", "#14532d"],
                                    size_max=18)
                fig_sc.update_traces(textposition="top center", marker_size=14)
                st.plotly_chart(theme(fig_sc), use_container_width=True)

    render_footer()


# ══════════════════════════════════════════════════════════════════════════════
#  Page 9 — Downloads
# ══════════════════════════════════════════════════════════════════════════════

def page_downloads() -> None:
    """Download individual CSVs or full ZIP bundle."""
    st.markdown(
        """
<div class="hero">
  <div class="hero-title">📥 Downloads</div>
  <p class="hero-sub">Download individual tables or bundle everything into a single ZIP archive.</p>
</div>
""",
        unsafe_allow_html=True,
    )

    # ── Individual table downloads ────────────────────────────────────────────
    section_title("Synthetic Tables")
    for t in TABLES:
        icon  = TABLE_ICONS[t]
        df_s  = load_csv(synth_path(t))
        df_o  = load_csv(orig_path(t))
        bs    = read_bytes(synth_path(t))
        bo    = read_bytes(orig_path(t))

        with st.container():
            glass_card(
                f'<b style="color:#e2e8f0">{icon} {t.capitalize()}</b>'
                f'<span style="font-size:.75rem;color:#475569;margin-left:.8rem">'
                f'{f"{len(df_s):,} synthetic rows · {len(df_s.columns)} cols" if df_s is not None else "Synthetic: not generated"}'
                f' &nbsp;|&nbsp; '
                f'{f"{len(df_o):,} original rows" if df_o is not None else "Original: not found"}'
                f'</span>'
            )
            c1, c2, _ = st.columns([1, 1, 3])
            with c1:
                if bs:
                    download_button(bs, f"synthetic_{t}.csv", f"⬇ Synthetic {t.capitalize()}")
                else:
                    st.caption("Synthetic CSV not found")
            with c2:
                if bo:
                    download_button(bo, f"{t}_ready.csv", f"⬇ Original {t.capitalize()}")
                else:
                    st.caption("Original CSV not found")

    # ── Evaluation downloads ──────────────────────────────────────────────────
    section_title("Evaluation Outputs")
    ev_files = [
        ("evaluation_summary.csv",  "⬇ Scores CSV",       "text/csv"),
        ("evaluation_summary.json", "⬇ Full JSON",         "application/json"),
        ("report.html",             "⬇ HTML Report",       "text/html"),
    ]
    ecols = st.columns(len(ev_files))
    for col, (fname, label, mime) in zip(ecols, ev_files):
        b = read_bytes(str(PROJECT_ROOT / "outputs" / "evaluation" / fname))
        with col:
            if b:
                download_button(b, fname, label, mime=mime)
            else:
                st.caption(f"{fname} not found")

    # ── ZIP bundle ────────────────────────────────────────────────────────────
    section_title("Full ZIP Bundle")
    zc1, zc2 = st.columns([1, 2])

    with zc1:
        if st.button("📦 Build ZIP Archive", key="zip_build"):
            with st.spinner("Building archive…"):
                buf = BytesIO()
                with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
                    for t in TABLES:
                        for src, dest in [
                            (synth_path(t), f"synthetic/synthetic_{t}.csv"),
                            (orig_path(t),  f"original/{t}_ready.csv"),
                        ]:
                            if Path(src).exists():
                                zf.write(src, dest)
                    ev_dir = PROJECT_ROOT / "outputs" / "evaluation"
                    for fname in ["evaluation_summary.csv", "evaluation_summary.json", "report.html"]:
                        p = ev_dir / fname
                        if p.exists():
                            zf.write(str(p), f"evaluation/{fname}")
                buf.seek(0)
                st.download_button(
                    "⬇ Download ZIP",
                    data=buf.read(),
                    file_name=f"synthfhir_dataset_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip",
                    mime="application/zip",
                    key="zip_dl",
                )

    with zc2:
        glass_card(
            """
<div style="font-size:.82rem;color:#94a3b8">The ZIP archive contains:</div>
<ul style="font-size:.78rem;color:#64748b;margin:.5rem 0 0;padding-left:1.1rem;line-height:2">
  <li><code>synthetic/*.csv</code> — Generated synthetic tables</li>
  <li><code>original/*.csv</code> — Preprocessed originals</li>
  <li><code>evaluation/evaluation_summary.csv</code></li>
  <li><code>evaluation/evaluation_summary.json</code></li>
  <li><code>evaluation/report.html</code></li>
</ul>
"""
        )

    render_footer()


# ══════════════════════════════════════════════════════════════════════════════
#  Page 10 — About
# ══════════════════════════════════════════════════════════════════════════════

def page_about() -> None:
    """Project overview, architecture, metrics, tech stack, roadmap."""
    st.markdown(
        """
<div class="hero">
  <div class="hero-title">ℹ️ About SynthFHIR</div>
  <p class="hero-sub">
    A production-grade pipeline for generating privacy-safe synthetic EHR data from
    real FHIR records using SDV's deep generative models — with full statistical
    evaluation and an interactive analytics platform.
  </p>
</div>
""",
        unsafe_allow_html=True,
    )

    cl, cr = st.columns(2)

    with cl:
        section_title("Problem Statement")
        glass_card(
            '<p style="font-size:.82rem;color:#94a3b8;line-height:1.75;margin:0">'
            "Real patient data is protected by HIPAA and similar regulations. "
            "SynthFHIR generates statistically equivalent synthetic records that preserve "
            "clinical distributions, inter-table relationships, and temporal sequences "
            "— without exposing any real patient information. The result is a dataset "
            "safe for ML research, vendor testing, staff training, and open publication."
            "</p>"
        )

        section_title("Synthesis Architecture")
        glass_card(
            """
<table style="width:100%;border-collapse:collapse;font-size:.79rem;color:#94a3b8">
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc;white-space:nowrap">Patients</td>
    <td style="padding:5px 8px">GaussianCopulaSynthesizer — robust tabular demographics</td></tr>
<tr style="background:rgba(255,255,255,.025)">
    <td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Encounters</td>
    <td style="padding:5px 8px">PARSynthesizer — temporal sequences per patient</td></tr>
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Observations</td>
    <td style="padding:5px 8px">PARSynthesizer — longitudinal vital sign trends</td></tr>
<tr style="background:rgba(255,255,255,.025)">
    <td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Conditions</td>
    <td style="padding:5px 8px">CTGANSynthesizer — conditional GAN for ICD codes</td></tr>
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Medications</td>
    <td style="padding:5px 8px">CTGANSynthesizer — high-cardinality drug descriptions</td></tr>
</table>
"""
        )

    with cr:
        section_title("Evaluation Metrics")
        glass_card(
            """
<table style="width:100%;border-collapse:collapse;font-size:.79rem;color:#94a3b8">
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc;white-space:nowrap">KS Statistic</td>
    <td style="padding:5px 8px">Kolmogorov–Smirnov 2-sample test for numeric columns</td></tr>
<tr style="background:rgba(255,255,255,.025)">
    <td style="padding:5px 8px;font-weight:700;color:#7dd3fc">TVD</td>
    <td style="padding:5px 8px">Total Variation Distance for categorical fidelity</td></tr>
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Pearson</td>
    <td style="padding:5px 8px">Correlation matrix preservation (mean |Δ|)</td></tr>
<tr style="background:rgba(255,255,255,.025)">
    <td style="padding:5px 8px;font-weight:700;color:#7dd3fc">Privacy</td>
    <td style="padding:5px 8px">Uniqueness × (1 − exact row overlap)</td></tr>
<tr><td style="padding:5px 8px;font-weight:700;color:#7dd3fc">SDV Quality</td>
    <td style="padding:5px 8px">SDV built-in evaluate_quality() report</td></tr>
</table>
"""
        )

        section_title("Technology Stack")
        glass_card(
            '<div style="font-size:.79rem;color:#94a3b8;line-height:2.1">'
            "🐍 <b style='color:#7dd3fc'>Python 3.10+</b><br>"
            "📊 <b style='color:#7dd3fc'>SDV 1.37</b> — PAR, CTGAN, GaussianCopulaSynthesizer<br>"
            "🔥 <b style='color:#7dd3fc'>PyTorch 2.x</b> — GPU-accelerated synthesis<br>"
            "🐼 <b style='color:#7dd3fc'>Pandas 2.x + NumPy</b> — data processing<br>"
            "📉 <b style='color:#7dd3fc'>Scipy + scikit-learn</b> — statistical evaluation<br>"
            "🌐 <b style='color:#7dd3fc'>Streamlit + Plotly</b> — this dashboard<br>"
            "🧬 <b style='color:#7dd3fc'>fhir.resources</b> — FHIR R4 parsing"
            "</div>"
        )

    section_title("Phase 5.2 Roadmap")
    glass_card(
        '<div style="font-size:.82rem;color:#94a3b8;line-height:1.95">'
        "🔲 <b style='color:#e2e8f0'>TSTR</b> — Train-on-Synthetic, Test-on-Real downstream ML benchmark<br>"
        "🔲 <b style='color:#e2e8f0'>Anonymeter</b> — singling-out, linkability and inference risk scores<br>"
        "🔲 <b style='color:#e2e8f0'>Membership Inference Attack</b> — shadow model privacy audit<br>"
        "🔲 <b style='color:#e2e8f0'>Temporal Pattern Evaluation</b> — ICD-10 sequence fidelity<br>"
        "🔲 <b style='color:#e2e8f0'>Conditional Sampling API</b> — cohort-matched generation<br>"
        "🔲 <b style='color:#e2e8f0'>FHIR R4 Export</b> — re-serialize synthetic records to JSON bundles<br>"
        "🔲 <b style='color:#e2e8f0'>Differential Privacy</b> — ε-DP guarantees for released datasets"
        "</div>"
    )

    render_footer()


# ══════════════════════════════════════════════════════════════════════════════
#  Main router
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    """Application entry-point: inject CSS, render sidebar, route to page."""
    inject_css()
    choice = render_sidebar()

    page_map = {
        "🏠  Dashboard":    page_dashboard,
        "👤  Patients":     lambda: page_dataset("patients"),
        "🏥  Encounters":   lambda: page_dataset("encounters"),
        "🔬  Observations": lambda: page_dataset("observations"),
        "💊  Conditions":   lambda: page_dataset("conditions"),
        "💉  Medications":  lambda: page_dataset("medications"),
        "📊  Evaluation":   page_evaluation,
        "📈  Analytics":    page_analytics,
        "📥  Downloads":    page_downloads,
        "ℹ️  About":        page_about,
    }

    fn = page_map.get(choice, page_dashboard)
    fn()


if __name__ == "__main__":
    main()
